spring:
  application:
    name: TaskManager
  datasource:
    url: jdbc:postgresql://task-manager-backend-db:5432/task-manager-backend-db
    username: postgres
    password: 267115

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true

