spring:
  application:
    name: TaskManager
  datasource:
    url: jdbc:postgresql://task-manager-backend-db:5432/task-manager-backend-db
    username: postgres
    password: 267115

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/task-manager
          jwk-set-uri: http://keycloak:8080/realms/task-manager/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://localhost:8180
  realm: task-manager
  resource: task-manager-client
  credentials:
    secret: